### ISSUE TITLE
缺少AdSupport框架

### ISSUE THREAD

**Issue by TouSC** [CodeEagle/ShareSDKSlim#1]

**Comment by CodeEagle** [comment]
已修复


 ### Subspecs
  s.subspec 'SinaWeibo' do |sinaweibos|
    sinaweibos.requires_arc = true
    sinaweibos.dependency 'ShareSDKSlim/Core'
    sinaweibos.frameworks = 'ImageIO','ADSupport'
    sinaweibos.source_files   = "libraries/extends/SinaWeiboSDK/*.h"
    sinaweibos.vendored_libraries = 'libraries/extends/SinaWeiboSDK/libWeiboSDK.a'
    sinaweibos.resources = "libraries/extends/SinaWeiboSDK/WeiboSDK.bundle"
  end

3.1.1.a
