### ISSUE TITLE
简洁版的官网最新版本是3.1.2，这里没有更新

### ISSUE THREAD

**Issue by donly** [CodeEagle/ShareSDKSlim#2]
请求更新，谢谢

**Comment by CodeEagle** [comment]
好的

**Comment by CodeEagle** [comment]
官方有podspec了，可以直接用 https://github.com/ShareSDKPlatform/ShareSDK/blob/master/ShareSDK.podspec

**Comment by donly** [comment]
Oh, no!

请不要删除，你说的官方版本也不是最新 *s.version          = "3.1.1"*。
而且不是简洁版，而你的这个是 ShareSDK**Slim**。

**Comment by CodeEagle** [comment]
3.1.2，他们简洁版就是3.x，这个就先保留了

**Comment by donly** [comment]
简洁版最新版是 3.1.2，pods 都没有更新，只有这个版本才支持 bitcode 请求更新，

**Comment by CodeEagle** [comment]
更新了
